# Generated by Django 4.1.5 on 2023-04-12 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('off_name', models.CharField(max_length=50)),
                ('off_post', models.CharField(max_length=50)),
                ('off_desc', models.TextField()),
                ('off_img', models.ImageField(default='', upload_to='image/')),
            ],
        ),
    ]
